services:
  web:
    build: .
    ports:
      - "3000:3000"
  postgres:
    image: postgres:16
    container_name: postgres_wfd
    restart: always
    environment:
      POSTGRES_USER: wfduser
      POSTGRES_PASSWORD: wfduser
      POSTGRES_DB: wfd
    volumes:
      - postgres_data:/var/lib/postgresql@16/data
    ports:
      - "5433:5432"

volumes:
  postgres_data: